#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
server:
  port: 8762
  #context-path: /service-hi
spring:
  application:
    name: service-hi
  zipkin:
    base-url: http://localhost:9411
  sleuth:
      sampler:
        percentage: 1.0
