eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
  #context-path: /service-feign
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true